DL-2483 - most recent years
fiduciary-benchmarks/form5500 pull request #25
Opened 2023-08-11 23:14 UTC by Steven-FDI

Card: [DL-2483](https://fbidev.atlassian.net/browse/DL-2483) (Form5500) Year adjustment

Tested locally. Doesn't see 2023 data, continues on and succeeds using an extra year since the current failed.

2023-08-11 23:21 UTC, Gavin-FDI approved these changes
Looks good, just left one small comment

2023-08-11 23:21 UTC, Gavin-FDI commented on import.go
> +	for i := 0; i < 6; i++ {
It might be a good idea to make the `6` used in the two places a constant with a descriptive name like `yearRange` or something.

2023-08-11 23:45 UTC, Brad-FDI commented on import.go
> +	for i := 0; i < 6; i++ {
I'm not following, how does 2023 get in the list?

2023-08-11 23:53 UTC, Brad-FDI requested changes

2023-08-11 23:53 UTC, Brad-FDI commented on import.go
> +	for i := 0; i < 6; i++ {
I'm not following, how does 2023 get in the list?

2023-08-11 23:53 UTC, Brad-FDI commented on import.go
> +	for i := 0; i < 6; i++ {
How about instead of having 2 loops, do this logic:

start with current year
result, err := createAndPopulateTables(year, section)
year--
loop until 6 successes, or max of 7 attempts

2023-08-11 23:53 UTC, Brad-FDI commented on import.go
> +				return results, fmt.Errorf("received 404 for table: %v", tableName)
why pass the statusCode all the way out from createTable, when an err is already being returned?

2023-08-12 00:22 UTC, Steven-FDI commented on import.go
> +				return results, fmt.Errorf("received 404 for table: %v", tableName)
@Brad-FDI Because the error has a string that contains the error and the status code, I thought it would be better to pass separately than to try to extract it from the error message

2023-08-12 00:25 UTC, Steven-FDI commented on import.go
> +	for i := 0; i < 6; i++ {
2023 gets in the list because it's the current year. I made it so there was only one loop, and extracted 6 to the constant yearRange. @Brad-FDI @Gavin-FDI

2023-08-13 05:50 UTC, Brad-FDI requested changes

2023-08-13 05:50 UTC, Brad-FDI commented on import.go
> +	}
if currentYear is 2023, then currentYear - 1 is 2022.  2023 will not be added to the array using this logic.

I see you're handling currentYear separately below.  it's unexpected/unintuitive that the "years" array doesn't include one of the years.

2023-08-13 05:50 UTC, Brad-FDI commented on import.go
>  	}
this is still 2 loops
use one loop
start at current year
go for max of 7 years, but stop early as soon as 6 are successful.

2023-08-13 05:50 UTC, Brad-FDI commented on import.go
> +		runner, err, statusCode := createTable(tableName, year, section)
its unexpected that a function named "createTable" would return an HTTP status code.  this tells me that the function is doing some else than creating a table.

2023-08-13 05:50 UTC, Brad-FDI commented on import.go
> +				return results, fmt.Errorf("received 404 for table: %v", tableName)
it is not better to return multiple values to present different kinds of error conditions, that would be unexpected.

ask ChatGPT this:  "if a Go function needs to return different errors as the err, and the calling code needs to decipher which error condition happened, what should the function return?"  There are a few options that don't involve parsing the err's string value.

2023-08-14 23:34 UTC, Steven-FDI commented on import.go
> +				return results, fmt.Errorf("received 404 for table: %v", tableName)
I just returned a specific error instead of the general error message, that way we can just check the error alone

2023-08-14 23:34 UTC, Steven-FDI commented on import.go
> +		runner, err, statusCode := createTable(tableName, year, section)
I adjusted the name

2023-08-18 18:45 UTC, Brad-FDI approved these changes

2023-08-18 20:18 UTC, merged